services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    restart: always

  auth:
    build: 
      context: .
      dockerfile: apps/auth/Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - 5000:8080
    networks:
      - default
    env_file:
      - .env
  
  user:
    build: 
      context: .
      dockerfile: apps/user/Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - 5001:8080
    networks:
      - default
    env_file:
      - .env

  nginx:
    image: nginx:1.21-alpine
    ports:
      - 8080:80
    depends_on:
      - auth
      - user
      - postgres
      - redis
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  
networks:
  default:
    driver: bridge
