services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    restart: always
    
networks:
  default:
    driver: bridge
